# librerias
# library(parallel)
# library(doParallel)
# cluster <- makeCluster(detectCores() - 1)
# registerDoParallel(cluster)

# Carga de librerias
#suppressPackageStartupMessages({
library(data.table)
library(dplyr)
library(caret)
library(scales)
library(ggplot2)
library(stringi)
library(stringr)
library(dataPreparation)
library(knitr)
library(kableExtra)
library(ggpubr)
library(tictoc)
library(ggeasy)
library(lubridate)
library(inspectdf)
library(ranger)
library(gbm)
library(tidyr)
library(corrplot)
library(Hmisc)
library(car)
library(questionr)
library(rpart)
library(caret)
library(MASS)
library(randomForest)
library(RColorBrewer)
library(psych)
library(caretEnsemble)
library(rpart.plot)
library(corrplot)

#})